# Generated by Django 4.2.6 on 2023-10-18 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("team_guess", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("league", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Riddle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.CharField(max_length=200)),
                ("formation", models.CharField(max_length=200)),
                ("result", models.CharField(max_length=200)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club",
                        to="team_guess.club",
                    ),
                ),
                (
                    "enemy_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enemy_club",
                        to="team_guess.club",
                    ),
                ),
                (
                    "player_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_1",
                        to="team_guess.country",
                    ),
                ),
                (
                    "player_10",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_10",
                        to="team_guess.country",
                    ),
                ),
                (
                    "player_11",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_11",
                        to="team_guess.country",
                    ),
                ),
                (
                    "player_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_2",
                        to="team_guess.country",
                    ),
                ),
                (
                    "player_3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_3",
                        to="team_guess.country",
                    ),
                ),
                (
                    "player_4",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_4",
                        to="team_guess.country",
                    ),
                ),
                (
                    "player_5",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_5",
                        to="team_guess.country",
                    ),
                ),
                (
                    "player_6",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_6",
                        to="team_guess.country",
                    ),
                ),
                (
                    "player_7",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_7",
                        to="team_guess.country",
                    ),
                ),
                (
                    "player_8",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_8",
                        to="team_guess.country",
                    ),
                ),
                (
                    "player_9",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_9",
                        to="team_guess.country",
                    ),
                ),
            ],
        ),
    ]
