# Generated by Django 4.2.6 on 2023-10-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team_guess", "0002_club_riddle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="flag",
            field=models.ImageField(upload_to="team_guess/files/flags"),
        ),
    ]
